version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/backend
hooks:
  ApplicationStop:
    - location: scripts/stop_service.sh
      timeout: 30
      runas: root

  ApplicationStart:
    - location: scripts/start_service.sh
      timeout: 30
      runas: root
